# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: device_utils.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    List,
    Optional,
)

import betterproto


class BrowserTlsFingerprintProtocolVersion(betterproto.Enum):
    """
    - RFC 5246 (TLS 1.2): https://tools.ietf.org/html/rfc5246
     - RFC 6101 (SSL 3.0): https://tools.ietf.org/html/rfc6101
     https://github.com/openssl/openssl/blob/c04e78f0c69201226430fed14c291c281da47f2d/include/openssl/prov_ssl.h
    """

    UNKNOWN = 0
    SSL3 = 768
    TLS1 = 769
    TLS1_1 = 770
    TLS1_2 = 771
    TLS1_3 = 772
    DTLS1 = 65279
    DTLS1_2 = 65277
    DTLS1_BAD = 256


class BrowserTlsFingerprintCipherSuite(betterproto.Enum):
    """
    - TLS cipher-suites: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4
    """

    TLS_NULL_WITH_NULL_NULL = 0
    TLS_RSA_WITH_NULL_MD5 = 1
    TLS_RSA_WITH_NULL_SHA = 2
    TLS_RSA_EXPORT_WITH_RC4_40_MD5 = 3
    TLS_RSA_WITH_RC4_128_MD5 = 4
    TLS_RSA_WITH_RC4_128_SHA = 5
    TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6
    TLS_RSA_WITH_IDEA_CBC_SHA = 7
    TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = 8
    TLS_RSA_WITH_DES_CBC_SHA = 9
    TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10
    TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11
    TLS_DH_DSS_WITH_DES_CBC_SHA = 12
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13
    TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14
    TLS_DH_RSA_WITH_DES_CBC_SHA = 15
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16
    TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17
    TLS_DHE_DSS_WITH_DES_CBC_SHA = 18
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19
    TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20
    TLS_DHE_RSA_WITH_DES_CBC_SHA = 21
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22
    TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23
    TLS_DH_anon_WITH_RC4_128_MD5 = 24
    TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25
    TLS_DH_anon_WITH_DES_CBC_SHA = 26
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27
    TLS_KRB5_WITH_DES_CBC_SHA = 30
    TLS_KRB5_WITH_3DES_EDE_CBC_SHA = 31
    TLS_KRB5_WITH_RC4_128_SHA = 32
    TLS_KRB5_WITH_IDEA_CBC_SHA = 33
    TLS_KRB5_WITH_DES_CBC_MD5 = 34
    TLS_KRB5_WITH_3DES_EDE_CBC_MD5 = 35
    TLS_KRB5_WITH_RC4_128_MD5 = 36
    TLS_KRB5_WITH_IDEA_CBC_MD5 = 37
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA = 38
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA = 39
    TLS_KRB5_EXPORT_WITH_RC4_40_SHA = 40
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 = 41
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5 = 42
    TLS_KRB5_EXPORT_WITH_RC4_40_MD5 = 43
    TLS_PSK_WITH_NULL_SHA = 44
    TLS_DHE_PSK_WITH_NULL_SHA = 45
    TLS_RSA_PSK_WITH_NULL_SHA = 46
    TLS_RSA_WITH_AES_128_CBC_SHA = 47
    TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48
    TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51
    TLS_DH_anon_WITH_AES_128_CBC_SHA = 52
    TLS_RSA_WITH_AES_256_CBC_SHA = 53
    TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54
    TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57
    TLS_DH_anon_WITH_AES_256_CBC_SHA = 58
    TLS_RSA_WITH_NULL_SHA256 = 59
    TLS_RSA_WITH_AES_128_CBC_SHA256 = 60
    TLS_RSA_WITH_AES_256_CBC_SHA256 = 61
    TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62
    TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA = 65
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA = 66
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA = 67
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA = 68
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA = 69
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA = 70
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103
    TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104
    TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107
    TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108
    TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA = 132
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA = 133
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA = 134
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA = 135
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA = 136
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA = 137
    TLS_PSK_WITH_RC4_128_SHA = 138
    TLS_PSK_WITH_3DES_EDE_CBC_SHA = 139
    TLS_PSK_WITH_AES_128_CBC_SHA = 140
    TLS_PSK_WITH_AES_256_CBC_SHA = 141
    TLS_DHE_PSK_WITH_RC4_128_SHA = 142
    TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 143
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 144
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 145
    TLS_RSA_PSK_WITH_RC4_128_SHA = 146
    TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 147
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 148
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 149
    TLS_RSA_WITH_SEED_CBC_SHA = 150
    TLS_DH_DSS_WITH_SEED_CBC_SHA = 151
    TLS_DH_RSA_WITH_SEED_CBC_SHA = 152
    TLS_DHE_DSS_WITH_SEED_CBC_SHA = 153
    TLS_DHE_RSA_WITH_SEED_CBC_SHA = 154
    TLS_DH_anon_WITH_SEED_CBC_SHA = 155
    TLS_RSA_WITH_AES_128_GCM_SHA256 = 156
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 157
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 158
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159
    TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 160
    TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 161
    TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 162
    TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163
    TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 164
    TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 165
    TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 166
    TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 167
    TLS_PSK_WITH_AES_128_GCM_SHA256 = 168
    TLS_PSK_WITH_AES_256_GCM_SHA384 = 169
    TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 170
    TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 171
    TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 172
    TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 173
    TLS_PSK_WITH_AES_128_CBC_SHA256 = 174
    TLS_PSK_WITH_AES_256_CBC_SHA384 = 175
    TLS_PSK_WITH_NULL_SHA256 = 176
    TLS_PSK_WITH_NULL_SHA384 = 177
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 178
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 179
    TLS_DHE_PSK_WITH_NULL_SHA256 = 180
    TLS_DHE_PSK_WITH_NULL_SHA384 = 181
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 182
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 183
    TLS_RSA_PSK_WITH_NULL_SHA256 = 184
    TLS_RSA_PSK_WITH_NULL_SHA384 = 185
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 186
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 187
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 188
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 189
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 190
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 = 191
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 192
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 193
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 194
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 195
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 196
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 = 197
    TLS_SM4_GCM_SM3 = 198
    TLS_SM4_CCM_SM3 = 199
    TLS_EMPTY_RENEGOTIATION_INFO_SCSV = 255
    Reserved = 2570
    Unassigned = 4864
    TLS_AES_128_GCM_SHA256 = 4865
    TLS_AES_256_GCM_SHA384 = 4866
    TLS_CHACHA20_POLY1305_SHA256 = 4867
    TLS_AES_128_CCM_SHA256 = 4868
    TLS_AES_128_CCM_8_SHA256 = 4869
    TLS_AEGIS_256_SHA384 = 4870
    TLS_AEGIS_128L_SHA256 = 4871
    TLS_FALLBACK_SCSV = 22016
    TLS_ECDH_ECDSA_WITH_NULL_SHA = 49153
    TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 49154
    TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 49155
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 49156
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 49157
    TLS_ECDHE_ECDSA_WITH_NULL_SHA = 49158
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 49159
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 49160
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 49161
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 49162
    TLS_ECDH_RSA_WITH_NULL_SHA = 49163
    TLS_ECDH_RSA_WITH_RC4_128_SHA = 49164
    TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 49165
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 49166
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 49167
    TLS_ECDHE_RSA_WITH_NULL_SHA = 49168
    TLS_ECDHE_RSA_WITH_RC4_128_SHA = 49169
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 49170
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 49171
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 49172
    TLS_ECDH_anon_WITH_NULL_SHA = 49173
    TLS_ECDH_anon_WITH_RC4_128_SHA = 49174
    TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 49175
    TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 49176
    TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 49177
    TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA = 49178
    TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA = 49179
    TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA = 49180
    TLS_SRP_SHA_WITH_AES_128_CBC_SHA = 49181
    TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA = 49182
    TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA = 49183
    TLS_SRP_SHA_WITH_AES_256_CBC_SHA = 49184
    TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA = 49185
    TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA = 49186
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 49187
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 49188
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 49189
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 49190
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 49191
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 49192
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 49193
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 49194
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196
    TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 49197
    TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 49198
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200
    TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 49201
    TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 49202
    TLS_ECDHE_PSK_WITH_RC4_128_SHA = 49203
    TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA = 49204
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 49205
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 49206
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 = 49207
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 = 49208
    TLS_ECDHE_PSK_WITH_NULL_SHA = 49209
    TLS_ECDHE_PSK_WITH_NULL_SHA256 = 49210
    TLS_ECDHE_PSK_WITH_NULL_SHA384 = 49211
    TLS_RSA_WITH_ARIA_128_CBC_SHA256 = 49212
    TLS_RSA_WITH_ARIA_256_CBC_SHA384 = 49213
    TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256 = 49214
    TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384 = 49215
    TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256 = 49216
    TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384 = 49217
    TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256 = 49218
    TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384 = 49219
    TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49220
    TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49221
    TLS_DH_anon_WITH_ARIA_128_CBC_SHA256 = 49222
    TLS_DH_anon_WITH_ARIA_256_CBC_SHA384 = 49223
    TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49224
    TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49225
    TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49226
    TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49227
    TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49228
    TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49229
    TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256 = 49230
    TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384 = 49231
    TLS_RSA_WITH_ARIA_128_GCM_SHA256 = 49232
    TLS_RSA_WITH_ARIA_256_GCM_SHA384 = 49233
    TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49234
    TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49235
    TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256 = 49236
    TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384 = 49237
    TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256 = 49238
    TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384 = 49239
    TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256 = 49240
    TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384 = 49241
    TLS_DH_anon_WITH_ARIA_128_GCM_SHA256 = 49242
    TLS_DH_anon_WITH_ARIA_256_GCM_SHA384 = 49243
    TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49244
    TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49245
    TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49246
    TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49247
    TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49248
    TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49249
    TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256 = 49250
    TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384 = 49251
    TLS_PSK_WITH_ARIA_128_CBC_SHA256 = 49252
    TLS_PSK_WITH_ARIA_256_CBC_SHA384 = 49253
    TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49254
    TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49255
    TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256 = 49256
    TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384 = 49257
    TLS_PSK_WITH_ARIA_128_GCM_SHA256 = 49258
    TLS_PSK_WITH_ARIA_256_GCM_SHA384 = 49259
    TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256 = 49260
    TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384 = 49261
    TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256 = 49262
    TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384 = 49263
    TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49264
    TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49265
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49266
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49267
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49268
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49269
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49270
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49271
    TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49272
    TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49273
    TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49274
    TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49275
    TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49276
    TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49277
    TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49278
    TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49279
    TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49280
    TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49281
    TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49282
    TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49283
    TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256 = 49284
    TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384 = 49285
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49286
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49287
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49288
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49289
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49290
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49291
    TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49292
    TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49293
    TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49294
    TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49295
    TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49296
    TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49297
    TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49298
    TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49299
    TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49300
    TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49301
    TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49302
    TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49303
    TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49304
    TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49305
    TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49306
    TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49307
    TLS_RSA_WITH_AES_128_CCM = 49308
    TLS_RSA_WITH_AES_256_CCM = 49309
    TLS_DHE_RSA_WITH_AES_128_CCM = 49310
    TLS_DHE_RSA_WITH_AES_256_CCM = 49311
    TLS_RSA_WITH_AES_128_CCM_8 = 49312
    TLS_RSA_WITH_AES_256_CCM_8 = 49313
    TLS_DHE_RSA_WITH_AES_128_CCM_8 = 49314
    TLS_DHE_RSA_WITH_AES_256_CCM_8 = 49315
    TLS_PSK_WITH_AES_128_CCM = 49316
    TLS_PSK_WITH_AES_256_CCM = 49317
    TLS_DHE_PSK_WITH_AES_128_CCM = 49318
    TLS_DHE_PSK_WITH_AES_256_CCM = 49319
    TLS_PSK_WITH_AES_128_CCM_8 = 49320
    TLS_PSK_WITH_AES_256_CCM_8 = 49321
    TLS_PSK_DHE_WITH_AES_128_CCM_8 = 49322
    TLS_PSK_DHE_WITH_AES_256_CCM_8 = 49323
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM = 49324
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM = 49325
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 = 49326
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 = 49327
    TLS_ECCPWD_WITH_AES_128_GCM_SHA256 = 49328
    TLS_ECCPWD_WITH_AES_256_GCM_SHA384 = 49329
    TLS_ECCPWD_WITH_AES_128_CCM_SHA256 = 49330
    TLS_ECCPWD_WITH_AES_256_CCM_SHA384 = 49331
    TLS_SHA256_SHA256 = 49332
    TLS_SHA384_SHA384 = 49333
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC = 49408
    TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC = 49409
    TLS_GOSTR341112_256_WITH_28147_CNT_IMIT = 49410
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L = 49411
    TLS_GOSTR341112_256_WITH_MAGMA_MGM_L = 49412
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_S = 49413
    TLS_GOSTR341112_256_WITH_MAGMA_MGM_S = 49414
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393
    TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52394
    TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52395
    TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52396
    TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52397
    TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52398
    TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 = 53249
    TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384 = 53250
    TLS_ECDHE_PSK_WITH_AES_128_CCM_8_SHA256 = 53251
    TLS_ECDHE_PSK_WITH_AES_128_CCM_SHA256 = 53253


class BrowserTlsFingerprintExtensions(betterproto.Enum):
    """
    - TLS extensions: https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml
    """

    SERVER_NAME = 0
    MAX_FRAGMENT_LENGTH = 1
    CLIENT_CERTIFICATE_URL = 2
    TRUSTED_CA_KEYS = 3
    TRUNCATED_HMAC = 4
    STATUS_REQUEST = 5
    USER_MAPPING = 6
    CLIENT_AUTHZ = 7
    SERVER_AUTHZ = 8
    CERT_TYPE = 9
    SUPPORTED_GROUPS = 10
    EC_POINT_FORMATS = 11
    SRP = 12
    SIGNATURE_ALGORITHMS = 13
    USE_SRTP = 14
    HEARTBEAT = 15
    APPLICATION_LAYER_PROTOCOL_NEGOTIATION = 16
    STATUS_REQUEST_V2 = 17
    SIGNED_CERTIFICATE_TIMESTAMP = 18
    CLIENT_CERTIFICATE_TYPE = 19
    SERVER_CERTIFICATE_TYPE = 20
    PADDING = 21
    ENCRYPT_THEN_MAC = 22
    EXTENDED_MASTER_SECRET = 23
    TOKEN_BINDING = 24
    CACHED_INFO = 25
    TLS_LTS = 26
    COMPRESS_CERTIFICATE = 27
    RECORD_SIZE_LIMIT = 28
    PWD_PROTECT = 29
    PWD_CLEAR = 30
    PASSWORD_SALT = 31
    TICKET_PINNING = 32
    TLS_CERT_WITH_EXTERN_PSK = 33
    DELEGATED_CREDENTIAL = 34
    SESSION_TICKET = 35
    TLMSP = 36
    TLMSP_PROXYING = 37
    TLMSP_DELEGATE = 38
    SUPPORTED_EKT_CIPHERS = 39
    PRE_SHARED_KEY = 41
    EARLY_DATA = 42
    SUPPORTED_VERSIONS = 43
    COOKIE = 44
    PSK_KEY_EXCHANGE_MODES = 45
    CERTIFICATE_AUTHORITIES = 47
    OID_FILTERS = 48
    POST_HANDSHAKE_AUTH = 49
    SIGNATURE_ALGORITHMS_CERT = 50
    KEY_SHARE = 51
    TRANSPARENCY_INFO = 52
    CONNECTION_ID_DEPRECATED = 53
    CONNECTION_ID = 54
    EXTERNAL_ID_HASH = 55
    EXTERNAL_SESSION_ID = 56
    QUIC_TRANSPORT_PARAMETERS = 57
    TICKET_REQUEST = 58
    DNSSEC_CHAIN = 59
    SEQUENCE_NUMBER_ENCRYPTION_ALGORITHMS = 60
    EXTENSION_APPLICATIONS_SETTINGS = 17513
    """src: boringssl"""

    EXTENSION_RENEGOTIATION_INFO = 65281


class BrowserTlsFingerprintEllipticCurve(betterproto.Enum):
    """
    - Elliptic curves: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8
    """

    RESERVED = 0
    SECT163K1 = 1
    SECT163R1 = 2
    SECT163R2 = 3
    SECT193R1 = 4
    SECT193R2 = 5
    SECT233K1 = 6
    SECT233R1 = 7
    SECT239K1 = 8
    SECT283K1 = 9
    SECT283R1 = 10
    SECT409K1 = 11
    SECT409R1 = 12
    SECT571K1 = 13
    SECT571R1 = 14
    SECP160K1 = 15
    SECP160R1 = 16
    SECP160R2 = 17
    SECP192K1 = 18
    SECP192R1 = 19
    SECP224K1 = 20
    SECP224R1 = 21
    SECP256K1 = 22
    SECP256R1 = 23
    SECP384R1 = 24
    SECP521R1 = 25
    BRAINPOOLP256R1 = 26
    BRAINPOOLP384R1 = 27
    BRAINPOOLP512R1 = 28
    X25519 = 29
    X448 = 30
    BRAINPOOLP256R1TLS13 = 31
    BRAINPOOLP384R1TLS13 = 32
    BRAINPOOLP512R1TLS13 = 33
    GC256A = 34
    GC256B = 35
    GC256C = 36
    GC256D = 37
    GC512A = 38
    GC512B = 39
    GC512C = 40
    CURVESM2 = 41
    FFDHE2048 = 256
    FFDHE3072 = 257
    FFDHE4096 = 258
    FFDHE6144 = 259
    FFDHE8192 = 260
    ARBITRARY_EXPLICIT_PRIME_CURVES = 65281
    ARBITRARY_EXPLICIT_CHAR2_CURVES = 65282


class BrowserTlsFingerprintEllipticCurvePointFormat(betterproto.Enum):
    """https://www.rfc-editor.org/rfc/rfc4492#section-5.1.2"""

    UNCOMPRESSED = 0
    ANSI_X962_COMPRESSED_PRIME = 1
    ANSI_X962_COMPRESSED_CHAR2 = 2


class GpsLocationLocationProvider(betterproto.Enum):
    LocationProvider_NONE = 0
    GPS = 1
    NETWORK = 2
    PASSIVE = 3


class CpuDataArchitecture(betterproto.Enum):
    UNKNOWN = 0
    ARM = 1
    ARM64 = 2
    MIPS = 3
    MIPSEL = 4
    PPC = 5
    PPC64 = 6
    X32 = 7
    X64 = 8


class AndroidDeviceVersion(betterproto.Enum):
    """
    Src: https://apilevels.com/
     BuildNumber defaults: https://source.android.com/docs/setup/about/build-numbers#source-code-tags-and-builds
    """

    AndroidVersion_NONE = 0
    V1_0 = 1
    V1_1 = 2
    V1_5 = 3
    V1_6 = 4
    V2 = 5
    V2_0_1 = 6
    V2_1 = 7
    V2_2 = 8
    V2_3_2 = 9
    V2_3_7 = 10
    V3_0 = 11
    v3_1 = 12
    V3_2 = 13
    V4_0_2 = 14
    V4_0_4 = 15
    V4_1 = 16
    V4_2 = 17
    V4_3 = 18
    V4_4 = 19
    V4_4W = 20
    V5_0 = 21
    V5_1 = 22
    V6_0 = 23
    V7_0 = 24
    V7_1 = 25
    V8_0 = 26
    V8_1 = 27
    V9_0 = 28
    V10_0 = 29
    V11_0 = 30
    V12_0 = 31
    V12_0L = 32
    V13_0 = 33
    V14_0 = 34


@dataclass(eq=False, repr=False)
class Browser(betterproto.Message):
    version: Optional[str] = betterproto.string_field(1, optional=True)
    name: Optional[str] = betterproto.string_field(2, optional=True)
    user_agent: Optional[str] = betterproto.string_field(
        3, optional=True, name="userAgent"
    )
    brand_header: Optional[str] = betterproto.string_field(
        4, optional=True, name="brandHeader"
    )
    tls_fingerprint: Optional["BrowserTlsFingerprint"] = betterproto.message_field(
        5, optional=True, name="tlsFingerprint"
    )
    app_code_name: Optional[str] = betterproto.string_field(
        20, optional=True, name="appCodeName"
    )
    """src: https://kaliiiiiiiiii.github.io/driverless-fp-collector/"""

    app_name: Optional[str] = betterproto.string_field(
        21, optional=True, name="appName"
    )
    app_version: Optional[str] = betterproto.string_field(
        22, optional=True, name="appVersion"
    )
    cookie_enabled: Optional[bool] = betterproto.bool_field(
        23, optional=True, name="cookieEnabled"
    )
    device_memory: Optional[int] = betterproto.int32_field(
        24, optional=True, name="deviceMemory"
    )
    do_not_track: Optional[int] = betterproto.int32_field(
        25, optional=True, name="doNotTrack"
    )
    hardware_concurrency: Optional[int] = betterproto.int32_field(
        26, optional=True, name="hardwareConcurrency"
    )
    language: Optional[str] = betterproto.string_field(27, optional=True)
    languages: Optional[List[str]] = betterproto.string_field(28, optional=True)
    max_touch_points: Optional[int] = betterproto.int32_field(
        29, optional=True, name="maxTouchPoints"
    )
    pdf_viewer_enabled: Optional[bool] = betterproto.bool_field(
        30, optional=True, name="pdfViewerEnabled"
    )
    platform: Optional[str] = betterproto.string_field(31, optional=True)
    product: Optional[str] = betterproto.string_field(32, optional=True)
    product_sub: Optional[str] = betterproto.string_field(
        33, optional=True, name="productSub"
    )
    vendor: Optional[str] = betterproto.string_field(34, optional=True)
    vendor_sub: Optional[str] = betterproto.string_field(
        35, optional=True, name="vendorSub"
    )
    webdriver: Optional[bool] = betterproto.bool_field(36, optional=True)
    device_pixel_ratio: Optional[float] = betterproto.double_field(
        37, optional=True, name="devicePixelRatio"
    )
    inner_width: Optional[int] = betterproto.int32_field(
        38, optional=True, name="innerWidth"
    )
    inner_height: Optional[int] = betterproto.int32_field(
        39, optional=True, name="innerHeight"
    )
    outer_width: Optional[int] = betterproto.int32_field(
        40, optional=True, name="outerWidth"
    )
    outer_height: Optional[int] = betterproto.int32_field(
        41, optional=True, name="outerHeight"
    )
    screen: Optional["BrowserBrowserScreen"] = betterproto.message_field(
        42, optional=True
    )
    web_gpu: Optional["BrowserWebGpu"] = betterproto.message_field(
        43, optional=True, name="webGPU"
    )
    speech_synthesis: Optional[List["BrowserSpeechSynthesis"]] = (
        betterproto.message_field(44, optional=True, name="speechSynthesis")
    )
    available_fonts: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        100, optional=True, name="availableFonts"
    )
    navigator: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        101, optional=True
    )
    window: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        102, optional=True
    )
    document: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        103, optional=True
    )
    document_element: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        104, optional=True, name="documentElement"
    )
    audio_types: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        105, optional=True, name="audioTypes"
    )
    video_types: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        106, optional=True, name="videoTypes"
    )
    css: Optional["BrowserBrowserCollection"] = betterproto.message_field(
        107, optional=True
    )


@dataclass(eq=False, repr=False)
class BrowserTlsFingerprint(betterproto.Message):
    version: Optional["BrowserTlsFingerprintProtocolVersion"] = betterproto.enum_field(
        1, optional=True
    )
    cipher_suites: Optional[List["BrowserTlsFingerprintCipherSuite"]] = (
        betterproto.enum_field(2, optional=True, name="cipherSuites")
    )
    extensions: Optional[List["BrowserTlsFingerprintExtensions"]] = (
        betterproto.enum_field(3, optional=True)
    )
    elliptic_curves: Optional[List["BrowserTlsFingerprintEllipticCurve"]] = (
        betterproto.enum_field(4, optional=True, name="ellipticCurves")
    )
    elliptic_curve_point_formats: Optional[
        List["BrowserTlsFingerprintEllipticCurvePointFormat"]
    ] = betterproto.enum_field(5, optional=True, name="ellipticCurvePointFormats")


@dataclass(eq=False, repr=False)
class BrowserBrowserCollection(betterproto.Message):
    hash: Optional[str] = betterproto.string_field(1, optional=True)
    list_data: Optional[List[str]] = betterproto.string_field(
        2, optional=True, name="listData"
    )
    map_data: Optional[Dict[str, str]] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING, optional=True
    )


@dataclass(eq=False, repr=False)
class BrowserBrowserScreen(betterproto.Message):
    avail_width: Optional[int] = betterproto.int32_field(
        1, optional=True, name="availWidth"
    )
    avail_height: Optional[int] = betterproto.int32_field(
        2, optional=True, name="availHeight"
    )
    width: Optional[int] = betterproto.int32_field(3, optional=True)
    height: Optional[int] = betterproto.int32_field(4, optional=True)
    color_depth: Optional[int] = betterproto.int32_field(
        5, optional=True, name="colorDepth"
    )
    pixel_depth: Optional[int] = betterproto.int32_field(
        6, optional=True, name="pixelDepth"
    )
    avail_left: Optional[int] = betterproto.int32_field(
        7, optional=True, name="availLeft"
    )
    avail_top: Optional[int] = betterproto.int32_field(
        8, optional=True, name="availTop"
    )
    is_extended: Optional[bool] = betterproto.bool_field(
        9, optional=True, name="isExtended"
    )
    orientation: Optional["BrowserBrowserScreenOrientation"] = (
        betterproto.message_field(10, optional=True)
    )


@dataclass(eq=False, repr=False)
class BrowserBrowserScreenOrientation(betterproto.Message):
    angle: Optional[int] = betterproto.int32_field(1, optional=True)
    type: Optional[str] = betterproto.string_field(2, optional=True)


@dataclass(eq=False, repr=False)
class BrowserWebGpu(betterproto.Message):
    features: Optional["BrowserWebGpuFeatures"] = betterproto.message_field(
        1, optional=True
    )
    limits: Optional["BrowserWebGpuLimits"] = betterproto.message_field(
        2, optional=True
    )
    is_fallback_adapter: Optional[bool] = betterproto.bool_field(
        3, optional=True, name="isFallbackAdapter"
    )
    vendor: Optional[str] = betterproto.string_field(4, optional=True)
    architecture: Optional[str] = betterproto.string_field(5, optional=True)
    device: Optional[str] = betterproto.string_field(6, optional=True)
    description: Optional[str] = betterproto.string_field(7, optional=True)


@dataclass(eq=False, repr=False)
class BrowserWebGpuFeatures(betterproto.Message):
    size: Optional[int] = betterproto.int32_field(1, optional=True)


@dataclass(eq=False, repr=False)
class BrowserWebGpuLimits(betterproto.Message):
    max_texture_dimension1_d: Optional[int] = betterproto.int32_field(
        1, optional=True, name="maxTextureDimension1D"
    )
    max_texture_dimension2_d: Optional[int] = betterproto.int32_field(
        2, optional=True, name="maxTextureDimension2D"
    )
    max_texture_dimension3_d: Optional[int] = betterproto.int32_field(
        3, optional=True, name="maxTextureDimension3D"
    )
    max_texture_array_layers: Optional[int] = betterproto.int32_field(
        4, optional=True, name="maxTextureArrayLayers"
    )
    max_bind_groups: Optional[int] = betterproto.int32_field(
        5, optional=True, name="maxBindGroups"
    )
    max_bindings_per_bind_group: Optional[int] = betterproto.int32_field(
        6, optional=True, name="maxBindingsPerBindGroup"
    )
    max_dynamic_uniform_buffers_per_pipeline_layout: Optional[int] = (
        betterproto.int32_field(
            7, optional=True, name="maxDynamicUniformBuffersPerPipelineLayout"
        )
    )
    max_dynamic_storage_buffers_per_pipeline_layout: Optional[int] = (
        betterproto.int32_field(
            8, optional=True, name="maxDynamicStorageBuffersPerPipelineLayout"
        )
    )
    max_sampled_textures_per_shader_stage: Optional[int] = betterproto.int32_field(
        9, optional=True, name="maxSampledTexturesPerShaderStage"
    )
    max_samplers_per_shader_stage: Optional[int] = betterproto.int32_field(
        10, optional=True, name="maxSamplersPerShaderStage"
    )
    max_storage_buffers_per_shader_stage: Optional[int] = betterproto.int32_field(
        11, optional=True, name="maxStorageBuffersPerShaderStage"
    )
    max_storage_textures_per_shader_stage: Optional[int] = betterproto.int32_field(
        12, optional=True, name="maxStorageTexturesPerShaderStage"
    )
    max_uniform_buffers_per_shader_stage: Optional[int] = betterproto.int32_field(
        13, optional=True, name="maxUniformBuffersPerShaderStage"
    )
    max_uniform_buffer_binding_size: Optional[int] = betterproto.int32_field(
        14, optional=True, name="maxUniformBufferBindingSize"
    )
    max_storage_buffer_binding_size: Optional[int] = betterproto.int32_field(
        15, optional=True, name="maxStorageBufferBindingSize"
    )
    min_uniform_buffer_offset_alignment: Optional[int] = betterproto.int32_field(
        16, optional=True, name="minUniformBufferOffsetAlignment"
    )
    min_storage_buffer_offset_alignment: Optional[int] = betterproto.int32_field(
        17, optional=True, name="minStorageBufferOffsetAlignment"
    )
    max_vertex_buffers: Optional[int] = betterproto.int32_field(
        18, optional=True, name="maxVertexBuffers"
    )
    max_buffer_size: Optional[int] = betterproto.int32_field(
        19, optional=True, name="maxBufferSize"
    )
    max_vertex_attributes: Optional[int] = betterproto.int32_field(
        20, optional=True, name="maxVertexAttributes"
    )
    max_vertex_buffer_array_stride: Optional[int] = betterproto.int32_field(
        21, optional=True, name="maxVertexBufferArrayStride"
    )
    max_inter_stage_shader_components: Optional[int] = betterproto.int32_field(
        22, optional=True, name="maxInterStageShaderComponents"
    )
    max_inter_stage_shader_variables: Optional[int] = betterproto.int32_field(
        23, optional=True, name="maxInterStageShaderVariables"
    )
    max_color_attachments: Optional[int] = betterproto.int32_field(
        24, optional=True, name="maxColorAttachments"
    )
    max_color_attachment_bytes_per_sample: Optional[int] = betterproto.int32_field(
        25, optional=True, name="maxColorAttachmentBytesPerSample"
    )
    max_compute_workgroup_storage_size: Optional[int] = betterproto.int32_field(
        26, optional=True, name="maxComputeWorkgroupStorageSize"
    )
    max_compute_invocations_per_workgroup: Optional[int] = betterproto.int32_field(
        27, optional=True, name="maxComputeInvocationsPerWorkgroup"
    )
    max_compute_workgroup_size_x: Optional[int] = betterproto.int32_field(
        28, optional=True, name="maxComputeWorkgroupSizeX"
    )
    max_compute_workgroup_size_y: Optional[int] = betterproto.int32_field(
        29, optional=True, name="maxComputeWorkgroupSizeY"
    )
    max_compute_workgroup_size_z: Optional[int] = betterproto.int32_field(
        30, optional=True, name="maxComputeWorkgroupSizeZ"
    )
    max_compute_workgroups_per_dimension: Optional[int] = betterproto.int32_field(
        31, optional=True, name="maxComputeWorkgroupsPerDimension"
    )


@dataclass(eq=False, repr=False)
class BrowserSpeechSynthesis(betterproto.Message):
    voice_uri: Optional[str] = betterproto.string_field(
        1, optional=True, name="voiceURI"
    )
    name: Optional[str] = betterproto.string_field(2, optional=True)
    lang: Optional[str] = betterproto.string_field(3, optional=True)
    local_service: Optional[bool] = betterproto.bool_field(
        4, optional=True, name="localService"
    )
    default: Optional[bool] = betterproto.bool_field(5, optional=True)


@dataclass(eq=False, repr=False)
class GpsLocation(betterproto.Message):
    """Potentially common for more than just Android"""

    longitude: Optional[float] = betterproto.double_field(1, optional=True)
    latitude: Optional[float] = betterproto.double_field(2, optional=True)
    altitude: Optional[float] = betterproto.double_field(3, optional=True)
    provider: Optional["GpsLocationLocationProvider"] = betterproto.enum_field(
        4, optional=True
    )


@dataclass(eq=False, repr=False)
class Locale(betterproto.Message):
    language: Optional[str] = betterproto.string_field(1, optional=True)
    country_iso: Optional[str] = betterproto.string_field(
        2, optional=True, name="countryISO"
    )


@dataclass(eq=False, repr=False)
class SimCard(betterproto.Message):
    phone_number: Optional[str] = betterproto.string_field(
        1, optional=True, name="phoneNumber"
    )
    """With or without country code?"""

    mcc: Optional[str] = betterproto.string_field(2, optional=True, name="MCC")
    """Provider and country information"""

    mnc: Optional[str] = betterproto.string_field(3, optional=True, name="MNC")
    carrier: Optional[str] = betterproto.string_field(4, optional=True)
    country_iso: Optional[str] = betterproto.string_field(
        5, optional=True, name="countryISO"
    )
    country_code: Optional[str] = betterproto.string_field(
        6, optional=True, name="countryCode"
    )
    imei: Optional["SimCardImei"] = betterproto.message_field(7, optional=True)
    meid: Optional["SimCardMeid"] = betterproto.message_field(8, optional=True)


@dataclass(eq=False, repr=False)
class SimCardImei(betterproto.Message):
    tac: Optional[str] = betterproto.string_field(1, optional=True, name="TAC")
    imei: Optional[str] = betterproto.string_field(2, optional=True)
    """
    src: https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity
     AA	-	BB	BB	BB	-	CC	CC	CC	D
     Where AA and BB = TAC, CC = serial (randomized) and D = Luhn validation
    """


@dataclass(eq=False, repr=False)
class SimCardMeid(betterproto.Message):
    region_code: Optional[str] = betterproto.string_field(
        1, optional=True, name="RegionCode"
    )
    manufacturer_code: Optional[str] = betterproto.string_field(
        2, optional=True, name="ManufacturerCode"
    )
    meid: Optional[str] = betterproto.string_field(3, optional=True)
    """
    src: https://en.wikipedia.org/wiki/Mobile_equipment_identifier
     R R	X	X	X	X	X	X	Z	Z	Z	Z	Z	Z	C
     Where R = region, X = manufacturer, Z = serial (randomized) and C = Luhn validation
    """


@dataclass(eq=False, repr=False)
class Mac(betterproto.Message):
    oui: Optional[str] = betterproto.string_field(1, optional=True, name="OUI")
    address: Optional[str] = betterproto.string_field(2, optional=True)


@dataclass(eq=False, repr=False)
class Timezone(betterproto.Message):
    name: Optional[str] = betterproto.string_field(1, optional=True)
    """IANA standard"""


@dataclass(eq=False, repr=False)
class ScreenData(betterproto.Message):
    density: Optional[int] = betterproto.int32_field(1, optional=True)
    resolution_horizontal: Optional[int] = betterproto.int32_field(
        2, optional=True, name="resolutionHorizontal"
    )
    resolution_vertical: Optional[int] = betterproto.int32_field(
        3, optional=True, name="resolutionVertical"
    )


@dataclass(eq=False, repr=False)
class CpuData(betterproto.Message):
    arch: Optional["CpuDataArchitecture"] = betterproto.enum_field(1, optional=True)
    arch_name: Optional[str] = betterproto.string_field(
        2, optional=True, name="archName"
    )
    model: Optional[str] = betterproto.string_field(3, optional=True)
    brand: Optional[str] = betterproto.string_field(4, optional=True)
    board: Optional[str] = betterproto.string_field(5, optional=True)
    abi_list: Optional[List[str]] = betterproto.string_field(
        6, optional=True, name="abiList"
    )


@dataclass(eq=False, repr=False)
class AndroidDevice(betterproto.Message):
    """Android device"""

    id: Optional["AndroidDeviceId"] = betterproto.message_field(1, optional=True)
    version: Optional["AndroidDeviceVersion"] = betterproto.enum_field(2, optional=True)
    build: Optional["AndroidDeviceBuildData"] = betterproto.message_field(
        3, optional=True
    )
    software: Optional["AndroidDeviceDeviceSoftware"] = betterproto.message_field(
        4, optional=True
    )
    screen: Optional["ScreenData"] = betterproto.message_field(5, optional=True)
    """
    Everything below this can technically be abstracted to unified device
    """

    cpu: Optional["CpuData"] = betterproto.message_field(6, optional=True)
    locale: Optional["Locale"] = betterproto.message_field(7, optional=True)
    location: Optional["GpsLocation"] = betterproto.message_field(8, optional=True)
    timezone: Optional["Timezone"] = betterproto.message_field(9, optional=True)
    mac_address: Optional["Mac"] = betterproto.message_field(
        10, optional=True, name="macAddress"
    )
    sim_slots: Optional[List["SimCard"]] = betterproto.message_field(
        11, optional=True, name="simSlots"
    )


@dataclass(eq=False, repr=False)
class AndroidDeviceId(betterproto.Message):
    id: Optional[int] = betterproto.uint64_field(1, optional=True)


@dataclass(eq=False, repr=False)
class AndroidDeviceBuildData(betterproto.Message):
    """https://developer.android.com/reference/android/os/Build"""

    board: Optional[str] = betterproto.string_field(1, optional=True)
    bootloader: Optional[str] = betterproto.string_field(2, optional=True)
    brand: Optional[str] = betterproto.string_field(3, optional=True)
    device: Optional[str] = betterproto.string_field(4, optional=True)
    display: Optional[str] = betterproto.string_field(5, optional=True)
    fingerprint: Optional[str] = betterproto.string_field(6, optional=True)
    hardware: Optional[str] = betterproto.string_field(7, optional=True)
    id: Optional[str] = betterproto.string_field(8, optional=True)
    manufacturer: Optional[str] = betterproto.string_field(9, optional=True)
    model: Optional[str] = betterproto.string_field(10, optional=True)
    odm_sku: Optional[str] = betterproto.string_field(11, optional=True, name="odmSku")
    product: Optional[str] = betterproto.string_field(12, optional=True)
    sku: Optional[str] = betterproto.string_field(13, optional=True)
    soc_manufacturer: Optional[str] = betterproto.string_field(
        14, optional=True, name="socManufacturer"
    )
    soc_model: Optional[str] = betterproto.string_field(
        15, optional=True, name="socModel"
    )
    tags: Optional[str] = betterproto.string_field(16, optional=True)
    type: Optional[str] = betterproto.string_field(17, optional=True)
    incremental_version: Optional[str] = betterproto.string_field(
        18, optional=True, name="incrementalVersion"
    )


@dataclass(eq=False, repr=False)
class AndroidDeviceDeviceSoftware(betterproto.Message):
    software_meta_data: Optional[Dict[str, str]] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING, optional=True
    )
    app_meta_data: Optional[Dict[str, str]] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING, optional=True
    )
    """app package : version string"""


Browser.__pydantic_model__.update_forward_refs()  # type: ignore
BrowserTlsFingerprint.__pydantic_model__.update_forward_refs()  # type: ignore
BrowserBrowserCollection.__pydantic_model__.update_forward_refs()  # type: ignore
BrowserBrowserScreen.__pydantic_model__.update_forward_refs()  # type: ignore
BrowserWebGpu.__pydantic_model__.update_forward_refs()  # type: ignore
GpsLocation.__pydantic_model__.update_forward_refs()  # type: ignore
SimCard.__pydantic_model__.update_forward_refs()  # type: ignore
CpuData.__pydantic_model__.update_forward_refs()  # type: ignore
AndroidDevice.__pydantic_model__.update_forward_refs()  # type: ignore
AndroidDeviceDeviceSoftware.__pydantic_model__.update_forward_refs()  # type: ignore
