# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: device_utils.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class BrowserTLSFingerprintProtocolVersion(betterproto.Enum):
    UNKNOWN = 0
    SSL3 = 768
    TLS1 = 769
    TLS1_1 = 770
    TLS1_2 = 771
    TLS1_3 = 772
    DTLS1 = 65279
    DTLS1_2 = 65277
    DTLS1_BAD = 256


class BrowserTLSFingerprintCipherSuite(betterproto.Enum):
    TLS_NULL_WITH_NULL_NULL = 0
    TLS_RSA_WITH_NULL_MD5 = 1
    TLS_RSA_WITH_NULL_SHA = 2
    TLS_RSA_EXPORT_WITH_RC4_40_MD5 = 3
    TLS_RSA_WITH_RC4_128_MD5 = 4
    TLS_RSA_WITH_RC4_128_SHA = 5
    TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6
    TLS_RSA_WITH_IDEA_CBC_SHA = 7
    TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = 8
    TLS_RSA_WITH_DES_CBC_SHA = 9
    TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10
    TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11
    TLS_DH_DSS_WITH_DES_CBC_SHA = 12
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13
    TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14
    TLS_DH_RSA_WITH_DES_CBC_SHA = 15
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16
    TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17
    TLS_DHE_DSS_WITH_DES_CBC_SHA = 18
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19
    TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20
    TLS_DHE_RSA_WITH_DES_CBC_SHA = 21
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22
    TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23
    TLS_DH_anon_WITH_RC4_128_MD5 = 24
    TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25
    TLS_DH_anon_WITH_DES_CBC_SHA = 26
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27
    TLS_KRB5_WITH_DES_CBC_SHA = 30
    TLS_KRB5_WITH_3DES_EDE_CBC_SHA = 31
    TLS_KRB5_WITH_RC4_128_SHA = 32
    TLS_KRB5_WITH_IDEA_CBC_SHA = 33
    TLS_KRB5_WITH_DES_CBC_MD5 = 34
    TLS_KRB5_WITH_3DES_EDE_CBC_MD5 = 35
    TLS_KRB5_WITH_RC4_128_MD5 = 36
    TLS_KRB5_WITH_IDEA_CBC_MD5 = 37
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA = 38
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA = 39
    TLS_KRB5_EXPORT_WITH_RC4_40_SHA = 40
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 = 41
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5 = 42
    TLS_KRB5_EXPORT_WITH_RC4_40_MD5 = 43
    TLS_PSK_WITH_NULL_SHA = 44
    TLS_DHE_PSK_WITH_NULL_SHA = 45
    TLS_RSA_PSK_WITH_NULL_SHA = 46
    TLS_RSA_WITH_AES_128_CBC_SHA = 47
    TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48
    TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51
    TLS_DH_anon_WITH_AES_128_CBC_SHA = 52
    TLS_RSA_WITH_AES_256_CBC_SHA = 53
    TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54
    TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57
    TLS_DH_anon_WITH_AES_256_CBC_SHA = 58
    TLS_RSA_WITH_NULL_SHA256 = 59
    TLS_RSA_WITH_AES_128_CBC_SHA256 = 60
    TLS_RSA_WITH_AES_256_CBC_SHA256 = 61
    TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62
    TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA = 65
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA = 66
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA = 67
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA = 68
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA = 69
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA = 70
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103
    TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104
    TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107
    TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108
    TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA = 132
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA = 133
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA = 134
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA = 135
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA = 136
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA = 137
    TLS_PSK_WITH_RC4_128_SHA = 138
    TLS_PSK_WITH_3DES_EDE_CBC_SHA = 139
    TLS_PSK_WITH_AES_128_CBC_SHA = 140
    TLS_PSK_WITH_AES_256_CBC_SHA = 141
    TLS_DHE_PSK_WITH_RC4_128_SHA = 142
    TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 143
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 144
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 145
    TLS_RSA_PSK_WITH_RC4_128_SHA = 146
    TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 147
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 148
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 149
    TLS_RSA_WITH_SEED_CBC_SHA = 150
    TLS_DH_DSS_WITH_SEED_CBC_SHA = 151
    TLS_DH_RSA_WITH_SEED_CBC_SHA = 152
    TLS_DHE_DSS_WITH_SEED_CBC_SHA = 153
    TLS_DHE_RSA_WITH_SEED_CBC_SHA = 154
    TLS_DH_anon_WITH_SEED_CBC_SHA = 155
    TLS_RSA_WITH_AES_128_GCM_SHA256 = 156
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 157
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 158
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159
    TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 160
    TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 161
    TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 162
    TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163
    TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 164
    TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 165
    TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 166
    TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 167
    TLS_PSK_WITH_AES_128_GCM_SHA256 = 168
    TLS_PSK_WITH_AES_256_GCM_SHA384 = 169
    TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 170
    TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 171
    TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 172
    TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 173
    TLS_PSK_WITH_AES_128_CBC_SHA256 = 174
    TLS_PSK_WITH_AES_256_CBC_SHA384 = 175
    TLS_PSK_WITH_NULL_SHA256 = 176
    TLS_PSK_WITH_NULL_SHA384 = 177
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 178
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 179
    TLS_DHE_PSK_WITH_NULL_SHA256 = 180
    TLS_DHE_PSK_WITH_NULL_SHA384 = 181
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 182
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 183
    TLS_RSA_PSK_WITH_NULL_SHA256 = 184
    TLS_RSA_PSK_WITH_NULL_SHA384 = 185
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 186
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 187
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 188
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 189
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 190
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 = 191
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 192
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 193
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 194
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 195
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 196
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 = 197
    TLS_SM4_GCM_SM3 = 198
    TLS_SM4_CCM_SM3 = 199
    TLS_EMPTY_RENEGOTIATION_INFO_SCSV = 255
    Reserved = 2570
    Unassigned = 4864
    TLS_AES_128_GCM_SHA256 = 4865
    TLS_AES_256_GCM_SHA384 = 4866
    TLS_CHACHA20_POLY1305_SHA256 = 4867
    TLS_AES_128_CCM_SHA256 = 4868
    TLS_AES_128_CCM_8_SHA256 = 4869
    TLS_AEGIS_256_SHA384 = 4870
    TLS_AEGIS_128L_SHA256 = 4871
    TLS_FALLBACK_SCSV = 22016
    TLS_ECDH_ECDSA_WITH_NULL_SHA = 49153
    TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 49154
    TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 49155
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 49156
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 49157
    TLS_ECDHE_ECDSA_WITH_NULL_SHA = 49158
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 49159
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 49160
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 49161
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 49162
    TLS_ECDH_RSA_WITH_NULL_SHA = 49163
    TLS_ECDH_RSA_WITH_RC4_128_SHA = 49164
    TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 49165
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 49166
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 49167
    TLS_ECDHE_RSA_WITH_NULL_SHA = 49168
    TLS_ECDHE_RSA_WITH_RC4_128_SHA = 49169
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 49170
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 49171
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 49172
    TLS_ECDH_anon_WITH_NULL_SHA = 49173
    TLS_ECDH_anon_WITH_RC4_128_SHA = 49174
    TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 49175
    TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 49176
    TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 49177
    TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA = 49178
    TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA = 49179
    TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA = 49180
    TLS_SRP_SHA_WITH_AES_128_CBC_SHA = 49181
    TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA = 49182
    TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA = 49183
    TLS_SRP_SHA_WITH_AES_256_CBC_SHA = 49184
    TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA = 49185
    TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA = 49186
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 49187
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 49188
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 49189
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 49190
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 49191
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 49192
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 49193
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 49194
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196
    TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 49197
    TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 49198
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200
    TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 49201
    TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 49202
    TLS_ECDHE_PSK_WITH_RC4_128_SHA = 49203
    TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA = 49204
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 49205
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 49206
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 = 49207
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 = 49208
    TLS_ECDHE_PSK_WITH_NULL_SHA = 49209
    TLS_ECDHE_PSK_WITH_NULL_SHA256 = 49210
    TLS_ECDHE_PSK_WITH_NULL_SHA384 = 49211
    TLS_RSA_WITH_ARIA_128_CBC_SHA256 = 49212
    TLS_RSA_WITH_ARIA_256_CBC_SHA384 = 49213
    TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256 = 49214
    TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384 = 49215
    TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256 = 49216
    TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384 = 49217
    TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256 = 49218
    TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384 = 49219
    TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49220
    TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49221
    TLS_DH_anon_WITH_ARIA_128_CBC_SHA256 = 49222
    TLS_DH_anon_WITH_ARIA_256_CBC_SHA384 = 49223
    TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49224
    TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49225
    TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49226
    TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49227
    TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49228
    TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49229
    TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256 = 49230
    TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384 = 49231
    TLS_RSA_WITH_ARIA_128_GCM_SHA256 = 49232
    TLS_RSA_WITH_ARIA_256_GCM_SHA384 = 49233
    TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49234
    TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49235
    TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256 = 49236
    TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384 = 49237
    TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256 = 49238
    TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384 = 49239
    TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256 = 49240
    TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384 = 49241
    TLS_DH_anon_WITH_ARIA_128_GCM_SHA256 = 49242
    TLS_DH_anon_WITH_ARIA_256_GCM_SHA384 = 49243
    TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49244
    TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49245
    TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49246
    TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49247
    TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49248
    TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49249
    TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256 = 49250
    TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384 = 49251
    TLS_PSK_WITH_ARIA_128_CBC_SHA256 = 49252
    TLS_PSK_WITH_ARIA_256_CBC_SHA384 = 49253
    TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49254
    TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49255
    TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256 = 49256
    TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384 = 49257
    TLS_PSK_WITH_ARIA_128_GCM_SHA256 = 49258
    TLS_PSK_WITH_ARIA_256_GCM_SHA384 = 49259
    TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256 = 49260
    TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384 = 49261
    TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256 = 49262
    TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384 = 49263
    TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49264
    TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49265
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49266
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49267
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49268
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49269
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49270
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49271
    TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49272
    TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49273
    TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49274
    TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49275
    TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49276
    TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49277
    TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49278
    TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49279
    TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49280
    TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49281
    TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49282
    TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49283
    TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256 = 49284
    TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384 = 49285
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49286
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49287
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49288
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49289
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49290
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49291
    TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49292
    TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49293
    TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49294
    TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49295
    TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49296
    TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49297
    TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49298
    TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49299
    TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49300
    TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49301
    TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49302
    TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49303
    TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49304
    TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49305
    TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49306
    TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49307
    TLS_RSA_WITH_AES_128_CCM = 49308
    TLS_RSA_WITH_AES_256_CCM = 49309
    TLS_DHE_RSA_WITH_AES_128_CCM = 49310
    TLS_DHE_RSA_WITH_AES_256_CCM = 49311
    TLS_RSA_WITH_AES_128_CCM_8 = 49312
    TLS_RSA_WITH_AES_256_CCM_8 = 49313
    TLS_DHE_RSA_WITH_AES_128_CCM_8 = 49314
    TLS_DHE_RSA_WITH_AES_256_CCM_8 = 49315
    TLS_PSK_WITH_AES_128_CCM = 49316
    TLS_PSK_WITH_AES_256_CCM = 49317
    TLS_DHE_PSK_WITH_AES_128_CCM = 49318
    TLS_DHE_PSK_WITH_AES_256_CCM = 49319
    TLS_PSK_WITH_AES_128_CCM_8 = 49320
    TLS_PSK_WITH_AES_256_CCM_8 = 49321
    TLS_PSK_DHE_WITH_AES_128_CCM_8 = 49322
    TLS_PSK_DHE_WITH_AES_256_CCM_8 = 49323
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM = 49324
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM = 49325
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 = 49326
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 = 49327
    TLS_ECCPWD_WITH_AES_128_GCM_SHA256 = 49328
    TLS_ECCPWD_WITH_AES_256_GCM_SHA384 = 49329
    TLS_ECCPWD_WITH_AES_128_CCM_SHA256 = 49330
    TLS_ECCPWD_WITH_AES_256_CCM_SHA384 = 49331
    TLS_SHA256_SHA256 = 49332
    TLS_SHA384_SHA384 = 49333
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC = 49408
    TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC = 49409
    TLS_GOSTR341112_256_WITH_28147_CNT_IMIT = 49410
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L = 49411
    TLS_GOSTR341112_256_WITH_MAGMA_MGM_L = 49412
    TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_S = 49413
    TLS_GOSTR341112_256_WITH_MAGMA_MGM_S = 49414
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393
    TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52394
    TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52395
    TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52396
    TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52397
    TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52398
    TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 = 53249
    TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384 = 53250
    TLS_ECDHE_PSK_WITH_AES_128_CCM_8_SHA256 = 53251
    TLS_ECDHE_PSK_WITH_AES_128_CCM_SHA256 = 53253


class BrowserTLSFingerprintExtensions(betterproto.Enum):
    SERVER_NAME = 0
    MAX_FRAGMENT_LENGTH = 1
    CLIENT_CERTIFICATE_URL = 2
    TRUSTED_CA_KEYS = 3
    TRUNCATED_HMAC = 4
    STATUS_REQUEST = 5
    USER_MAPPING = 6
    CLIENT_AUTHZ = 7
    SERVER_AUTHZ = 8
    CERT_TYPE = 9
    SUPPORTED_GROUPS = 10
    EC_POINT_FORMATS = 11
    SRP = 12
    SIGNATURE_ALGORITHMS = 13
    USE_SRTP = 14
    HEARTBEAT = 15
    APPLICATION_LAYER_PROTOCOL_NEGOTIATION = 16
    STATUS_REQUEST_V2 = 17
    SIGNED_CERTIFICATE_TIMESTAMP = 18
    CLIENT_CERTIFICATE_TYPE = 19
    SERVER_CERTIFICATE_TYPE = 20
    PADDING = 21
    ENCRYPT_THEN_MAC = 22
    EXTENDED_MASTER_SECRET = 23
    TOKEN_BINDING = 24
    CACHED_INFO = 25
    TLS_LTS = 26
    COMPRESS_CERTIFICATE = 27
    RECORD_SIZE_LIMIT = 28
    PWD_PROTECT = 29
    PWD_CLEAR = 30
    PASSWORD_SALT = 31
    TICKET_PINNING = 32
    TLS_CERT_WITH_EXTERN_PSK = 33
    DELEGATED_CREDENTIAL = 34
    SESSION_TICKET = 35
    TLMSP = 36
    TLMSP_PROXYING = 37
    TLMSP_DELEGATE = 38
    SUPPORTED_EKT_CIPHERS = 39
    PRE_SHARED_KEY = 41
    EARLY_DATA = 42
    SUPPORTED_VERSIONS = 43
    COOKIE = 44
    PSK_KEY_EXCHANGE_MODES = 45
    CERTIFICATE_AUTHORITIES = 47
    OID_FILTERS = 48
    POST_HANDSHAKE_AUTH = 49
    SIGNATURE_ALGORITHMS_CERT = 50
    KEY_SHARE = 51
    TRANSPARENCY_INFO = 52
    CONNECTION_ID_DEPRECATED = 53
    CONNECTION_ID = 54
    EXTERNAL_ID_HASH = 55
    EXTERNAL_SESSION_ID = 56
    QUIC_TRANSPORT_PARAMETERS = 57
    TICKET_REQUEST = 58
    DNSSEC_CHAIN = 59
    SEQUENCE_NUMBER_ENCRYPTION_ALGORITHMS = 60
    EXTENSION_APPLICATIONS_SETTINGS = 17513
    EXTENSION_RENEGOTIATION_INFO = 65281


class BrowserTLSFingerprintEllipticCurve(betterproto.Enum):
    RESERVED = 0
    SECT163K1 = 1
    SECT163R1 = 2
    SECT163R2 = 3
    SECT193R1 = 4
    SECT193R2 = 5
    SECT233K1 = 6
    SECT233R1 = 7
    SECT239K1 = 8
    SECT283K1 = 9
    SECT283R1 = 10
    SECT409K1 = 11
    SECT409R1 = 12
    SECT571K1 = 13
    SECT571R1 = 14
    SECP160K1 = 15
    SECP160R1 = 16
    SECP160R2 = 17
    SECP192K1 = 18
    SECP192R1 = 19
    SECP224K1 = 20
    SECP224R1 = 21
    SECP256K1 = 22
    SECP256R1 = 23
    SECP384R1 = 24
    SECP521R1 = 25
    BRAINPOOLP256R1 = 26
    BRAINPOOLP384R1 = 27
    BRAINPOOLP512R1 = 28
    X25519 = 29
    X448 = 30
    BRAINPOOLP256R1TLS13 = 31
    BRAINPOOLP384R1TLS13 = 32
    BRAINPOOLP512R1TLS13 = 33
    GC256A = 34
    GC256B = 35
    GC256C = 36
    GC256D = 37
    GC512A = 38
    GC512B = 39
    GC512C = 40
    CURVESM2 = 41
    FFDHE2048 = 256
    FFDHE3072 = 257
    FFDHE4096 = 258
    FFDHE6144 = 259
    FFDHE8192 = 260
    ARBITRARY_EXPLICIT_PRIME_CURVES = 65281
    ARBITRARY_EXPLICIT_CHAR2_CURVES = 65282


class BrowserTLSFingerprintEllipticCurvePointFormat(betterproto.Enum):
    UNCOMPRESSED = 0
    ANSI_X962_COMPRESSED_PRIME = 1
    ANSI_X962_COMPRESSED_CHAR2 = 2


class GPSLocationLocationProvider(betterproto.Enum):
    LocationProvider_NONE = 0
    GPS = 1
    NETWORK = 2
    PASSIVE = 3


class CPUDataArchitecture(betterproto.Enum):
    UNKNOWN = 0
    ARM = 1
    ARM64 = 2
    MIPS = 3
    MIPSEL = 4
    PPC = 5
    PPC64 = 6
    X32 = 7
    X64 = 8


class AndroidDeviceVersion(betterproto.Enum):
    AndroidVersion_NONE = 0
    V1_0 = 1
    V1_1 = 2
    V1_5 = 3
    V1_6 = 4
    V2 = 5
    V2_0_1 = 6
    V2_1 = 7
    V2_2 = 8
    V2_3_2 = 9
    V2_3_7 = 10
    V3_0 = 11
    v3_1 = 12
    V3_2 = 13
    V4_0_2 = 14
    V4_0_4 = 15
    V4_1 = 16
    V4_2 = 17
    V4_3 = 18
    V4_4 = 19
    V4_4W = 20
    V5_0 = 21
    V5_1 = 22
    V6_0 = 23
    V7_0 = 24
    V7_1 = 25
    V8_0 = 26
    V8_1 = 27
    V9_0 = 28
    V10_0 = 29
    V11_0 = 30
    V12_0 = 31
    V12_0L = 32
    V13_0 = 33
    V14_0 = 34


@dataclass
class Browser(betterproto.Message):
    version: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    user_agent: str = betterproto.string_field(3)
    brand_header: str = betterproto.string_field(4)
    tls_fingerprint: "BrowserTLSFingerprint" = betterproto.message_field(5)
    # src: https://kaliiiiiiiiii.github.io/driverless-fp-collector/
    app_code_name: str = betterproto.string_field(20)
    app_name: str = betterproto.string_field(21)
    app_version: str = betterproto.string_field(22)
    cookie_enabled: bool = betterproto.bool_field(23)
    device_memory: int = betterproto.int32_field(24)
    do_not_track: int = betterproto.int32_field(25)
    hardware_concurrency: int = betterproto.int32_field(26)
    language: str = betterproto.string_field(27)
    languages: List[str] = betterproto.string_field(28)
    max_touch_points: int = betterproto.int32_field(29)
    pdf_viewer_enabled: bool = betterproto.bool_field(30)
    platform: str = betterproto.string_field(31)
    product: str = betterproto.string_field(32)
    product_sub: str = betterproto.string_field(33)
    vendor: str = betterproto.string_field(34)
    vendor_sub: str = betterproto.string_field(35)
    webdriver: bool = betterproto.bool_field(36)
    device_pixel_ratio: float = betterproto.double_field(37)
    inner_width: int = betterproto.int32_field(38)
    inner_height: int = betterproto.int32_field(39)
    outer_width: int = betterproto.int32_field(40)
    outer_height: int = betterproto.int32_field(41)
    screen: "BrowserBrowserScreen" = betterproto.message_field(42)
    web_g_p_u: "BrowserWebGPU" = betterproto.message_field(43)
    speech_synthesis: List["BrowserSpeechSynthesis"] = betterproto.message_field(44)
    available_fonts: "BrowserBrowserCollection" = betterproto.message_field(100)
    navigator: "BrowserBrowserCollection" = betterproto.message_field(101)
    window: "BrowserBrowserCollection" = betterproto.message_field(102)
    document: "BrowserBrowserCollection" = betterproto.message_field(103)
    document_element: "BrowserBrowserCollection" = betterproto.message_field(104)
    audio_types: "BrowserBrowserCollection" = betterproto.message_field(105)
    video_types: "BrowserBrowserCollection" = betterproto.message_field(106)
    css: "BrowserBrowserCollection" = betterproto.message_field(107)


@dataclass
class BrowserTLSFingerprint(betterproto.Message):
    version: "BrowserTLSFingerprintProtocolVersion" = betterproto.enum_field(1)
    cipher_suites: List["BrowserTLSFingerprintCipherSuite"] = betterproto.enum_field(2)
    extensions: List["BrowserTLSFingerprintExtensions"] = betterproto.enum_field(3)
    elliptic_curves: List[
        "BrowserTLSFingerprintEllipticCurve"
    ] = betterproto.enum_field(4)
    elliptic_curve_point_formats: List[
        "BrowserTLSFingerprintEllipticCurvePointFormat"
    ] = betterproto.enum_field(5)


@dataclass
class BrowserBrowserCollection(betterproto.Message):
    hash: str = betterproto.string_field(1)
    list_data: List[str] = betterproto.string_field(2)
    map_data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class BrowserBrowserScreen(betterproto.Message):
    avail_width: int = betterproto.int32_field(1)
    avail_height: int = betterproto.int32_field(2)
    width: int = betterproto.int32_field(3)
    height: int = betterproto.int32_field(4)
    color_depth: int = betterproto.int32_field(5)
    pixel_depth: int = betterproto.int32_field(6)
    avail_left: int = betterproto.int32_field(7)
    avail_top: int = betterproto.int32_field(8)
    is_extended: bool = betterproto.bool_field(9)
    orientation: "BrowserBrowserScreenOrientation" = betterproto.message_field(10)


@dataclass
class BrowserBrowserScreenOrientation(betterproto.Message):
    angle: int = betterproto.int32_field(1)
    type: str = betterproto.string_field(2)


@dataclass
class BrowserWebGPU(betterproto.Message):
    features: "BrowserWebGPUFeatures" = betterproto.message_field(1)
    limits: "BrowserWebGPULimits" = betterproto.message_field(2)
    is_fallback_adapter: bool = betterproto.bool_field(3)
    vendor: str = betterproto.string_field(4)
    architecture: str = betterproto.string_field(5)
    device: str = betterproto.string_field(6)
    description: str = betterproto.string_field(7)


@dataclass
class BrowserWebGPUFeatures(betterproto.Message):
    size: int = betterproto.int32_field(1)


@dataclass
class BrowserWebGPULimits(betterproto.Message):
    max_texture_dimension1_d: int = betterproto.int32_field(1)
    max_texture_dimension2_d: int = betterproto.int32_field(2)
    max_texture_dimension3_d: int = betterproto.int32_field(3)
    max_texture_array_layers: int = betterproto.int32_field(4)
    max_bind_groups: int = betterproto.int32_field(5)
    max_bindings_per_bind_group: int = betterproto.int32_field(6)
    max_dynamic_uniform_buffers_per_pipeline_layout: int = betterproto.int32_field(7)
    max_dynamic_storage_buffers_per_pipeline_layout: int = betterproto.int32_field(8)
    max_sampled_textures_per_shader_stage: int = betterproto.int32_field(9)
    max_samplers_per_shader_stage: int = betterproto.int32_field(10)
    max_storage_buffers_per_shader_stage: int = betterproto.int32_field(11)
    max_storage_textures_per_shader_stage: int = betterproto.int32_field(12)
    max_uniform_buffers_per_shader_stage: int = betterproto.int32_field(13)
    max_uniform_buffer_binding_size: int = betterproto.int32_field(14)
    max_storage_buffer_binding_size: int = betterproto.int32_field(15)
    min_uniform_buffer_offset_alignment: int = betterproto.int32_field(16)
    min_storage_buffer_offset_alignment: int = betterproto.int32_field(17)
    max_vertex_buffers: int = betterproto.int32_field(18)
    max_buffer_size: int = betterproto.int32_field(19)
    max_vertex_attributes: int = betterproto.int32_field(20)
    max_vertex_buffer_array_stride: int = betterproto.int32_field(21)
    max_inter_stage_shader_components: int = betterproto.int32_field(22)
    max_inter_stage_shader_variables: int = betterproto.int32_field(23)
    max_color_attachments: int = betterproto.int32_field(24)
    max_color_attachment_bytes_per_sample: int = betterproto.int32_field(25)
    max_compute_workgroup_storage_size: int = betterproto.int32_field(26)
    max_compute_invocations_per_workgroup: int = betterproto.int32_field(27)
    max_compute_workgroup_size_x: int = betterproto.int32_field(28)
    max_compute_workgroup_size_y: int = betterproto.int32_field(29)
    max_compute_workgroup_size_z: int = betterproto.int32_field(30)
    max_compute_workgroups_per_dimension: int = betterproto.int32_field(31)


@dataclass
class BrowserSpeechSynthesis(betterproto.Message):
    voice_u_r_i: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    lang: str = betterproto.string_field(3)
    local_service: bool = betterproto.bool_field(4)
    default: bool = betterproto.bool_field(5)


@dataclass
class GPSLocation(betterproto.Message):
    """Potentially common for more than just Android"""

    longitude: float = betterproto.double_field(1)
    latitude: float = betterproto.double_field(2)
    altitude: float = betterproto.double_field(3)
    provider: "GPSLocationLocationProvider" = betterproto.enum_field(4)


@dataclass
class Locale(betterproto.Message):
    language: str = betterproto.string_field(1)
    country_i_s_o: str = betterproto.string_field(2)


@dataclass
class SIMCard(betterproto.Message):
    # With or without country code?
    phone_number: str = betterproto.string_field(1)
    # Provider and country information
    m_c_c: str = betterproto.string_field(2)
    m_n_c: str = betterproto.string_field(3)
    carrier: str = betterproto.string_field(4)
    country_i_s_o: str = betterproto.string_field(5)
    country_code: str = betterproto.string_field(6)
    imei: "SIMCardIMEI" = betterproto.message_field(7)
    meid: "SIMCardMEID" = betterproto.message_field(8)


@dataclass
class SIMCardIMEI(betterproto.Message):
    t_a_c: str = betterproto.string_field(1)
    # src: https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity
    # AA     -       BB      BB      BB      -       CC      CC      CC      D
    # Where AA and BB = TAC, CC = serial (randomized) and D = Luhn validation
    imei: str = betterproto.string_field(2)


@dataclass
class SIMCardMEID(betterproto.Message):
    region_code: str = betterproto.string_field(1)
    manufacturer_code: str = betterproto.string_field(2)
    # src: https://en.wikipedia.org/wiki/Mobile_equipment_identifier  R R    X
    # X       X       X       X       X       Z       Z       Z       Z       Z
    # Z       C  Where R = region, X = manufacturer, Z = serial (randomized) and
    # C = Luhn validation
    meid: str = betterproto.string_field(3)


@dataclass
class MAC(betterproto.Message):
    o_u_i: str = betterproto.string_field(1)
    address: str = betterproto.string_field(2)


@dataclass
class Timezone(betterproto.Message):
    # IANA standard
    name: str = betterproto.string_field(1)


@dataclass
class ScreenData(betterproto.Message):
    density: int = betterproto.int32_field(1)
    resolution_horizontal: int = betterproto.int32_field(2)
    resolution_vertical: int = betterproto.int32_field(3)


@dataclass
class CPUData(betterproto.Message):
    arch: "CPUDataArchitecture" = betterproto.enum_field(1)
    arch_name: str = betterproto.string_field(2)
    model: str = betterproto.string_field(3)
    brand: str = betterproto.string_field(4)
    board: str = betterproto.string_field(5)
    abi_list: List[str] = betterproto.string_field(6)


@dataclass
class AndroidDevice(betterproto.Message):
    """Android device"""

    id: "AndroidDeviceID" = betterproto.message_field(1)
    version: "AndroidDeviceVersion" = betterproto.enum_field(2)
    build: "AndroidDeviceBuildData" = betterproto.message_field(3)
    software: "AndroidDeviceDeviceSoftware" = betterproto.message_field(4)
    # Everything below this can technically be abstracted to unified device
    screen: "ScreenData" = betterproto.message_field(5)
    cpu: "CPUData" = betterproto.message_field(6)
    locale: "Locale" = betterproto.message_field(7)
    location: "GPSLocation" = betterproto.message_field(8)
    timezone: "Timezone" = betterproto.message_field(9)
    mac_address: "MAC" = betterproto.message_field(10)
    sim_slots: List["SIMCard"] = betterproto.message_field(11)


@dataclass
class AndroidDeviceID(betterproto.Message):
    id: int = betterproto.uint64_field(1)


@dataclass
class AndroidDeviceBuildData(betterproto.Message):
    """https://developer.android.com/reference/android/os/Build"""

    board: str = betterproto.string_field(1)
    bootloader: str = betterproto.string_field(2)
    brand: str = betterproto.string_field(3)
    device: str = betterproto.string_field(4)
    display: str = betterproto.string_field(5)
    fingerprint: str = betterproto.string_field(6)
    hardware: str = betterproto.string_field(7)
    id: str = betterproto.string_field(8)
    manufacturer: str = betterproto.string_field(9)
    model: str = betterproto.string_field(10)
    odm_sku: str = betterproto.string_field(11)
    product: str = betterproto.string_field(12)
    sku: str = betterproto.string_field(13)
    soc_manufacturer: str = betterproto.string_field(14)
    soc_model: str = betterproto.string_field(15)
    tags: str = betterproto.string_field(16)
    type: str = betterproto.string_field(17)
    incremental_version: str = betterproto.string_field(18)


@dataclass
class AndroidDeviceDeviceSoftware(betterproto.Message):
    software_meta_data: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    # app package : version string
    app_meta_data: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
